spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
    include:
      - vim
      - sys0
  server:
    port: 8080
    tomcat:
    # 强制使用 NIO nio2为：org.apache.coyote.http11.Http11Nio2Protocol
      protocol: org.apache.coyote.http11.Http11NioProtocol
      max-threads: 200        # 最大工作线程数
      accept-count: 100       # 连接队列长度
      connection-timeout: 20000  # 毫秒