spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
    include:
      - vim
      - sys0

  #author: fresleo
  #data：2025-11-6 
  #desciption： 设置tomcat的nio1 or nio2
  server:
    port: 8080
    tomcat:
    # 强制使用 NIO nio2为：org.apache.coyote.http11.Http11Nio2Protocol
      protocol: org.apache.coyote.http11.Http11Nio2Protocol
      max-threads: 200        # 最大工作线程数
      accept-count: 100       # 连接队列长度
      connection-timeout: 10000  # 毫秒
  threads:
    virtual:
      enabled: true  # 启用虚拟线程
      
aws:
  s3:
    endpoint: https://us-lax-1.linodeobjects.com
    accessKeyId: 1WGL5ZC292D8IL1EYXPX
    secretAccessKey: Wl8SMJl0Yvqqjicll4B8FQ8R6HxqLVFtw11gZYen
    region: us-lax-1
    bucketName: 01video
